#this is a locally hosted image that exists in the docker_go_ruby directory
FROM docker_go_ruby

CMD git clone https://github.com/jerren1122/docker_td_api_frontend.git; cd docker_td_api_frontend; cd api; go build; ./api;